# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 宋志诚的博客
subtitle: 爱折腾，瞎捣鼓，也是一个伪极客
description: 技术分享；人生随笔；
author: 宋志诚
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://nfeat.com' and root as '/child/'
url: http://nfeat.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 6
pagination_dir: page

# Extensions
Plugins: 
- hexo-generator-feed
- hexo-generator-sitemap  ## http://hexo.io/plugins/
- hexo-generator-baidu-sitemap
#!/bin/bash
## Themes: http://hexo.io/themes/
theme: yilia
rss: /atom.xml
#sitemap
sitemap:
  path: sitemap.xml

baidusitemap:
  path: baidusitemap.xml

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type:
